# Generated by Django 4.2.8 on 2023-12-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_item_url_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
