# Generated by Django 4.2.8 on 2023-12-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_discount_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.IntegerField(),
        ),
    ]
