# Generated by Django 4.2.8 on 2023-12-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_placed_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tax'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
